declare namespace Cloudflare {
  interface Env {
    DB: D1Database;
    MEDIA: R2Bucket;
    APP_URL?: string;
    INSTRUCTOR_AUTH_MODE?: string;
    OIDC_ISSUER?: string;
    OIDC_CLIENT_ID?: string;
    OIDC_TOKEN_ENDPOINT_AUTH_METHOD?: string;
    OIDC_ID_TOKEN_SIGNING_ALG?: string;
    AUTH_SESSION_LIFETIME_SECONDS?: string;
    OIDC_CLIENT_SECRET?: string;
    AUTH_SESSION_PEPPER?: string;
    AUTH_TRANSACTION_ENCRYPTION_KEY?: string;
    APPLICATION_WRITE_MODE?: string;
    STRIPE_SECRET_KEY?: string;
    STRIPE_WEBHOOK_SECRET?: string;
    STRIPE_CHECKOUT_PRICE_ID?: string;
    STRIPE_CHECKOUT_SESSION_LIFETIME_SECONDS?: string;
    BILLING_COMMERCIAL_POLICY_JSON?: string;
    STRIPE_RECOGNIZED_PRICE_IDS?: string;
    SUBSCRIPTION_ENTITLEMENT_PRICE_IDS?: string;
    SUBSCRIPTION_MAX_PROJECTION_AGE_SECONDS?: string;
    BILLING_CHECKOUT_ENABLED?: string;
    SHARE_TOKEN_PEPPER?: string;
    ABUSE_LIMIT_PEPPER?: string;
    CONSENT_POLICY_REGISTRY_JSON?: string;
    MEDIA_UPLOAD_POLICY_JSON?: string;
    INSTRUCTOR_ACCESS_MODE?: string;
    OWNER_PRIVATE_ACCESS_PEPPER?: string;
    OWNER_PRIVATE_EMAIL_DIGESTS?: string;
    DATA_REQUEST_OPERATOR_ACCESS_PEPPER?: string;
    DATA_REQUEST_OPERATOR_EMAIL_DIGESTS?: string;
    SUBSCRIPTION_ACCESS_STATUSES?: string;
    RELEASE_ID?: string;
    DEV_AUTH_EMAIL?: string;
    DEV_AUTH_NAME?: string;
  }
}
