declare namespace Cloudflare {
  interface Env {
    DB: D1Database;
    MEDIA: R2Bucket;
    APP_URL?: string;
    APPLICATION_WRITE_MODE?: string;
    STRIPE_SECRET_KEY?: string;
    STRIPE_WEBHOOK_SECRET?: string;
    STRIPE_CHECKOUT_PRICE_ID?: string;
    STRIPE_CHECKOUT_SESSION_LIFETIME_SECONDS?: string;
    STRIPE_RECOGNIZED_PRICE_IDS?: string;
    SUBSCRIPTION_ENTITLEMENT_PRICE_IDS?: string;
    SUBSCRIPTION_MAX_PROJECTION_AGE_SECONDS?: string;
    BILLING_CHECKOUT_ENABLED?: string;
    SHARE_TOKEN_PEPPER?: string;
    ABUSE_LIMIT_PEPPER?: string;
    CONSENT_POLICY_REGISTRY_JSON?: string;
    INSTRUCTOR_ACCESS_MODE?: string;
    OWNER_PRIVATE_ACCESS_PEPPER?: string;
    OWNER_PRIVATE_EMAIL_DIGESTS?: string;
    DATA_REQUEST_OPERATOR_ACCESS_PEPPER?: string;
    DATA_REQUEST_OPERATOR_EMAIL_DIGESTS?: string;
    SUBSCRIPTION_ACCESS_STATUSES?: string;
    RELEASE_ID?: string;
    DEV_AUTH_EMAIL?: string;
    DEV_AUTH_NAME?: string;
  }
}
