CREATE TABLE `scheduler_heartbeat` (
	`scheduler_key` text PRIMARY KEY NOT NULL,
	`attempt_token` text NOT NULL,
	`release_id` text NOT NULL,
	`state` text NOT NULL,
	`started_at` integer NOT NULL,
	`completed_at` integer,
	`billing_configured` integer,
	`considered_count` integer,
	`attempted_count` integer,
	`succeeded_count` integer,
	`failed_count` integer,
	`dead_letter_count` integer,
	`last_failure_code` text,
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5) * 86400000 as integer)) NOT NULL,
	CONSTRAINT "scheduler_heartbeat_singleton_check" CHECK("scheduler_heartbeat"."scheduler_key" = 'billing_reconciliation'),
	CONSTRAINT "scheduler_heartbeat_attempt_token_check" CHECK(length("scheduler_heartbeat"."attempt_token") between 1 and 128 and "scheduler_heartbeat"."attempt_token" not glob '*[^A-Za-z0-9._:-]*'),
	CONSTRAINT "scheduler_heartbeat_release_id_check" CHECK(length("scheduler_heartbeat"."release_id") between 1 and 128 and "scheduler_heartbeat"."release_id" not glob '*[^A-Za-z0-9._:-]*'),
	CONSTRAINT "scheduler_heartbeat_state_check" CHECK("scheduler_heartbeat"."state" in ('running', 'succeeded', 'failed')),
	CONSTRAINT "scheduler_heartbeat_completion_check" CHECK(("scheduler_heartbeat"."state" = 'running' and "scheduler_heartbeat"."completed_at" is null) or ("scheduler_heartbeat"."state" <> 'running' and "scheduler_heartbeat"."completed_at" is not null and "scheduler_heartbeat"."completed_at" >= "scheduler_heartbeat"."started_at")),
	CONSTRAINT "scheduler_heartbeat_result_shape_check" CHECK(("scheduler_heartbeat"."state" = 'succeeded' and "scheduler_heartbeat"."billing_configured" is not null and "scheduler_heartbeat"."considered_count" is not null and "scheduler_heartbeat"."attempted_count" is not null and "scheduler_heartbeat"."succeeded_count" is not null and "scheduler_heartbeat"."failed_count" is not null and "scheduler_heartbeat"."dead_letter_count" is not null and "scheduler_heartbeat"."last_failure_code" is null) or ("scheduler_heartbeat"."state" <> 'succeeded' and "scheduler_heartbeat"."billing_configured" is null and "scheduler_heartbeat"."considered_count" is null and "scheduler_heartbeat"."attempted_count" is null and "scheduler_heartbeat"."succeeded_count" is null and "scheduler_heartbeat"."failed_count" is null and "scheduler_heartbeat"."dead_letter_count" is null)),
	CONSTRAINT "scheduler_heartbeat_failure_check" CHECK(("scheduler_heartbeat"."state" = 'failed' and "scheduler_heartbeat"."last_failure_code" is not null and length("scheduler_heartbeat"."last_failure_code") between 1 and 64 and "scheduler_heartbeat"."last_failure_code" not glob '*[^a-z0-9_]*') or ("scheduler_heartbeat"."state" <> 'failed' and "scheduler_heartbeat"."last_failure_code" is null)),
	CONSTRAINT "scheduler_heartbeat_counts_check" CHECK("scheduler_heartbeat"."considered_count" is null or ("scheduler_heartbeat"."considered_count" >= 0 and "scheduler_heartbeat"."attempted_count" >= 0 and "scheduler_heartbeat"."succeeded_count" >= 0 and "scheduler_heartbeat"."failed_count" >= 0 and "scheduler_heartbeat"."dead_letter_count" >= 0 and "scheduler_heartbeat"."attempted_count" <= "scheduler_heartbeat"."considered_count" and "scheduler_heartbeat"."succeeded_count" + "scheduler_heartbeat"."failed_count" = "scheduler_heartbeat"."attempted_count"))
);
