import { sql } from "drizzle-orm";
import {
  check,
  foreignKey,
  index,
  integer,
  primaryKey,
  real,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

// D1 stores dates as integer Unix epoch milliseconds. Opaque, globally unique
// text IDs are generated by the application so records can be created at the edge.
const timestamp = (name: string) => integer(name, { mode: "timestamp_ms" });
const currentTimestampMs = sql`(cast((julianday('now') - 2440587.5) * 86400000 as integer))`;
const createdAt = () =>
  timestamp("created_at").notNull().default(currentTimestampMs);
const updatedAt = () =>
  timestamp("updated_at").notNull().default(currentTimestampMs);

export const accountStatuses = [
  "pending_verification",
  "active",
  "suspended",
  "deletion_pending",
  "deleted",
] as const;
export const mediaStatuses = [
  "pending",
  "ready",
  "failed",
  "quarantined",
  "deleted",
] as const;
export const subscriptionStatuses = [
  "incomplete",
  "trialing",
  "active",
  "past_due",
  "paused",
  "canceled",
  "unpaid",
  "ended",
] as const;
export const packageStatuses = ["draft", "active", "archived"] as const;
export const golferStatuses = [
  "active",
  "inactive",
  "archived",
  "deletion_pending",
  "deleted",
] as const;
export const planStatuses = [
  "draft",
  "preview_ready",
  "published",
  "paused",
  "completed",
  "archived",
] as const;
export const goalStatuses = [
  "active",
  "achieved",
  "revised",
  "archived",
] as const;
export const assessmentStatuses = [
  "draft",
  "confirmed",
  "superseded",
  "archived",
] as const;
export const priorityStatuses = [
  "active",
  "resolved",
  "deferred",
  "archived",
] as const;
export const phaseStatuses = [
  "planned",
  "active",
  "paused",
  "complete",
  "revised",
  "canceled",
] as const;
export const lessonStatuses = [
  "planned",
  "completed",
  "canceled",
  "archived",
] as const;
export const practiceStatuses = [
  "draft",
  "active",
  "completed",
  "paused",
  "retired",
] as const;
export const evidenceStatuses = [
  "draft",
  "published",
  "withdrawn",
  "archived",
] as const;
export const phaseReviewStatuses = [
  "draft",
  "confirmed",
  "shared",
  "superseded",
] as const;
export const shareLinkStatuses = [
  "active",
  "revoked",
  "expired",
] as const;
export const consentStatuses = [
  "granted",
  "declined",
  "withdrawn",
  "expired",
] as const;
export const billingEventStatuses = [
  "received",
  "processing",
  "processed",
  "ignored",
  "failed",
] as const;
export const billingCheckoutAttemptStatuses = [
  "reserved",
  "open",
  "completed_pending_sync",
  "completed",
  "expired",
  "quarantined",
] as const;
export const billingReconciliationTargetTypes = [
  "subscription",
  "checkout_attempt",
] as const;
export const billingReconciliationTargetStates = [
  "processing",
  "succeeded",
  "failed",
] as const;
export const schedulerHeartbeatStates = [
  "running",
  "succeeded",
  "failed",
] as const;
export const billingAccountOperationLeaseStates = ["idle", "held"] as const;
export const billingAccountOperationTypes = [
  "checkout",
  "reconciliation",
] as const;
export const dataRequestStatuses = [
  "submitted",
  "identity_verification_required",
  "verified",
  "in_progress",
  "fulfilled",
  "denied",
  "canceled",
  "failed",
] as const;

export const abuseLimitScopes = [
  "share_exchange_network",
  "share_exchange_capability",
  "share_close_network",
  "share_close_session",
  "share_response_network",
  "share_response_capability",
  "plan_publish_account",
  "share_revoke_account",
  "billing_checkout_account",
  "billing_portal_account",
  "billing_reconcile_account",
  "data_export_account",
  "data_request_account",
  "data_request_operator_network",
  "data_request_operator_identity",
] as const;

export const accounts = sqliteTable(
  "accounts",
  {
    id: text("id").primaryKey(),
    authProvider: text("auth_provider").notNull().default("siwc"),
    authSubject: text("auth_subject").notNull(),
    primaryEmail: text("primary_email").notNull(),
    normalizedEmail: text("normalized_email").notNull(),
    emailVerifiedAt: timestamp("email_verified_at"),
    status: text("status", { enum: accountStatuses })
      .notNull()
      .default("pending_verification"),
    locale: text("locale").notNull().default("en-CA"),
    timezone: text("timezone").notNull().default("America/Edmonton"),
    lastSignedInAt: timestamp("last_signed_in_at"),
    suspendedAt: timestamp("suspended_at"),
    suspensionReason: text("suspension_reason"),
    deletionScheduledAt: timestamp("deletion_scheduled_at"),
    deletedAt: timestamp("deleted_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex("accounts_auth_identity_unique").on(
      table.authProvider,
      table.authSubject,
    ),
    uniqueIndex("accounts_normalized_email_unique").on(table.normalizedEmail),
    index("accounts_status_idx").on(table.status),
    check(
      "accounts_status_check",
      sql`${table.status} in ('pending_verification', 'active', 'suspended', 'deletion_pending', 'deleted')`,
    ),
    check(
      "accounts_normalized_email_check",
      sql`${table.normalizedEmail} = lower(trim(${table.normalizedEmail}))`,
    ),
  ],
);

export const mediaAssets = sqliteTable(
  "media_assets",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    storageProvider: text("storage_provider").notNull(),
    objectKey: text("object_key").notNull(),
    status: text("status", { enum: mediaStatuses })
      .notNull()
      .default("pending"),
    mediaKind: text("media_kind", {
      enum: ["image", "video", "audio", "document"],
    }).notNull(),
    mimeType: text("mime_type").notNull(),
    originalFilename: text("original_filename"),
    byteSize: integer("byte_size").notNull(),
    contentSha256: text("content_sha256"),
    widthPixels: integer("width_pixels"),
    heightPixels: integer("height_pixels"),
    durationMs: integer("duration_ms"),
    altText: text("alt_text"),
    caption: text("caption"),
    transcript: text("transcript"),
    failureCode: text("failure_code"),
    uploadedAt: timestamp("uploaded_at"),
    processedAt: timestamp("processed_at"),
    deletedAt: timestamp("deleted_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex("media_assets_account_id_unique").on(table.accountId, table.id),
    uniqueIndex("media_assets_storage_object_unique").on(
      table.storageProvider,
      table.objectKey,
    ),
    index("media_assets_account_status_idx").on(table.accountId, table.status),
    index("media_assets_content_sha256_idx").on(
      table.accountId,
      table.contentSha256,
    ),
    check(
      "media_assets_status_check",
      sql`${table.status} in ('pending', 'ready', 'failed', 'quarantined', 'deleted')`,
    ),
    check(
      "media_assets_kind_check",
      sql`${table.mediaKind} in ('image', 'video', 'audio', 'document')`,
    ),
    check("media_assets_byte_size_check", sql`${table.byteSize} >= 0`),
    check(
      "media_assets_dimensions_check",
      sql`(${table.widthPixels} is null or ${table.widthPixels} > 0) and (${table.heightPixels} is null or ${table.heightPixels} > 0) and (${table.durationMs} is null or ${table.durationMs} >= 0)`,
    ),
  ],
);

export const instructorProfiles = sqliteTable(
  "instructor_profiles",
  {
    accountId: text("account_id")
      .primaryKey()
      .references(() => accounts.id, { onDelete: "cascade" }),
    displayName: text("display_name").notNull(),
    businessName: text("business_name"),
    professionalTitle: text("professional_title"),
    philosophy: text("philosophy"),
    contactEmail: text("contact_email").notNull(),
    contactPhone: text("contact_phone"),
    websiteUrl: text("website_url"),
    provinceOrTerritory: text("province_or_territory"),
    city: text("city"),
    accentColor: text("accent_color"),
    logoMediaAssetId: text("logo_media_asset_id"),
    profilePhotoMediaAssetId: text("profile_photo_media_asset_id"),
    setupCompletedAt: timestamp("setup_completed_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "instructor_profiles_logo_media_tenant_fk",
      columns: [table.accountId, table.logoMediaAssetId],
      foreignColumns: [mediaAssets.accountId, mediaAssets.id],
    }).onDelete("no action"),
    foreignKey({
      name: "instructor_profiles_photo_media_tenant_fk",
      columns: [table.accountId, table.profilePhotoMediaAssetId],
      foreignColumns: [mediaAssets.accountId, mediaAssets.id],
    }).onDelete("no action"),
    check(
      "instructor_profiles_accent_color_check",
      sql`${table.accentColor} is null or (length(${table.accentColor}) = 7 and substr(${table.accentColor}, 1, 1) = '#' and substr(${table.accentColor}, 2) not glob '*[^0-9A-Fa-f]*')`,
    ),
  ],
);

export const billingCustomers = sqliteTable(
  "billing_customers",
  {
    provider: text("provider").notNull(),
    providerCustomerId: text("provider_customer_id").notNull(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    primaryKey({
      name: "billing_customers_provider_customer_pk",
      columns: [table.provider, table.providerCustomerId],
    }),
    uniqueIndex("billing_customers_provider_account_unique").on(
      table.provider,
      table.accountId,
    ),
    uniqueIndex("billing_customers_tenant_reference_unique").on(
      table.provider,
      table.providerCustomerId,
      table.accountId,
    ),
    check(
      "billing_customers_provider_check",
      sql`${table.provider} = 'stripe'`,
    ),
  ],
);

export const billingSubscriptionProjectionGenerations = sqliteTable(
  "billing_subscription_projection_generations",
  {
    provider: text("provider").notNull(),
    providerSubscriptionId: text("provider_subscription_id").notNull(),
    generation: integer("generation").notNull().default(1),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    primaryKey({
      name: "billing_subscription_projection_generations_provider_subscription_pk",
      columns: [table.provider, table.providerSubscriptionId],
    }),
    check(
      "billing_subscription_projection_generations_provider_check",
      sql`${table.provider} = 'stripe'`,
    ),
    check(
      "billing_subscription_projection_generations_generation_check",
      sql`${table.generation} >= 1`,
    ),
  ],
);

export const billingCheckoutAttempts = sqliteTable(
  "billing_checkout_attempts",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    provider: text("provider").notNull().default("stripe"),
    state: text("state", { enum: billingCheckoutAttemptStatuses })
      .notNull()
      .default("reserved"),
    requestVersion: integer("request_version").notNull().default(1),
    idempotencyKey: text("idempotency_key").notNull(),
    providerPriceId: text("provider_price_id").notNull(),
    applicationOrigin: text("application_origin").notNull(),
    providerCustomerId: text("provider_customer_id"),
    customerEmail: text("customer_email").notNull(),
    providerSessionId: text("provider_session_id"),
    providerCreatedAt: timestamp("provider_created_at"),
    providerExpiresAt: timestamp("provider_expires_at").notNull(),
    completedAt: timestamp("completed_at"),
    expiredAt: timestamp("expired_at"),
    lastErrorCode: text("last_error_code"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "billing_checkout_attempts_customer_tenant_fk",
      columns: [
        table.provider,
        table.providerCustomerId,
        table.accountId,
      ],
      foreignColumns: [
        billingCustomers.provider,
        billingCustomers.providerCustomerId,
        billingCustomers.accountId,
      ],
    }).onDelete("no action"),
    uniqueIndex("billing_checkout_attempts_provider_key_unique").on(
      table.provider,
      table.idempotencyKey,
    ),
    uniqueIndex("billing_checkout_attempts_account_id_unique").on(
      table.accountId,
      table.id,
    ),
    uniqueIndex("billing_checkout_attempts_provider_session_unique")
      .on(table.provider, table.providerSessionId)
      .where(sql`${table.providerSessionId} is not null`),
    uniqueIndex("billing_checkout_attempts_one_blocking_per_account")
      .on(table.provider, table.accountId)
      .where(
        sql`${table.state} in ('reserved', 'open', 'completed_pending_sync', 'quarantined')`,
      ),
    index("billing_checkout_attempts_expiry_idx").on(
      table.state,
      table.providerExpiresAt,
    ),
    check(
      "billing_checkout_attempts_provider_check",
      sql`${table.provider} = 'stripe'`,
    ),
    check(
      "billing_checkout_attempts_state_check",
      sql`${table.state} in ('reserved', 'open', 'completed_pending_sync', 'completed', 'expired', 'quarantined')`,
    ),
    check(
      "billing_checkout_attempts_request_version_check",
      sql`${table.requestVersion} = 1`,
    ),
    check(
      "billing_checkout_attempts_expiry_check",
      sql`${table.providerExpiresAt} > ${table.createdAt}`,
    ),
    check(
      "billing_checkout_attempts_session_state_check",
      sql`${table.state} not in ('open', 'completed_pending_sync', 'completed') or ${table.providerSessionId} is not null`,
    ),
    check(
      "billing_checkout_attempts_completed_check",
      sql`(${table.state} = 'completed' and ${table.completedAt} is not null) or (${table.state} <> 'completed' and ${table.completedAt} is null)`,
    ),
    check(
      "billing_checkout_attempts_expired_check",
      sql`(${table.state} = 'expired' and ${table.expiredAt} is not null) or (${table.state} <> 'expired' and ${table.expiredAt} is null)`,
    ),
  ],
);

export const subscriptions = sqliteTable(
  "subscriptions",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    provider: text("provider").notNull(),
    providerCustomerId: text("provider_customer_id").notNull(),
    providerSubscriptionId: text("provider_subscription_id"),
    providerPriceId: text("provider_price_id"),
    productCode: text("product_code").notNull(),
    status: text("status", { enum: subscriptionStatuses })
      .notNull()
      .default("incomplete"),
    billingInterval: text("billing_interval", {
      enum: ["month", "year"],
    }),
    currency: text("currency"),
    unitAmountMinor: integer("unit_amount_minor"),
    trialStartsAt: timestamp("trial_starts_at"),
    trialEndsAt: timestamp("trial_ends_at"),
    currentPeriodStartsAt: timestamp("current_period_starts_at"),
    currentPeriodEndsAt: timestamp("current_period_ends_at"),
    cancelAtPeriodEnd: integer("cancel_at_period_end", { mode: "boolean" })
      .notNull()
      .default(false),
    cancelRequestedAt: timestamp("cancel_requested_at"),
    canceledAt: timestamp("canceled_at"),
    pauseStartsAt: timestamp("pause_starts_at"),
    pauseEndsAt: timestamp("pause_ends_at"),
    endedAt: timestamp("ended_at"),
    lastProviderSyncAt: timestamp("last_provider_sync_at"),
    projectionRevision: integer("projection_revision").notNull().default(1),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "subscriptions_customer_tenant_fk",
      columns: [table.provider, table.providerCustomerId, table.accountId],
      foreignColumns: [
        billingCustomers.provider,
        billingCustomers.providerCustomerId,
        billingCustomers.accountId,
      ],
    }).onDelete("no action"),
    uniqueIndex("subscriptions_account_id_unique").on(table.accountId, table.id),
    uniqueIndex("subscriptions_provider_subscription_unique")
      .on(table.provider, table.providerSubscriptionId)
      .where(sql`${table.providerSubscriptionId} is not null`),
    uniqueIndex("subscriptions_one_open_per_account")
      .on(table.accountId)
      .where(
        sql`${table.status} in ('incomplete', 'trialing', 'active', 'past_due', 'paused', 'unpaid')`,
      ),
    index("subscriptions_provider_status_sync_idx").on(
      table.provider,
      table.status,
      table.lastProviderSyncAt,
    ),
    index("subscriptions_account_status_idx").on(table.accountId, table.status),
    index("subscriptions_period_end_idx").on(table.currentPeriodEndsAt),
    check(
      "subscriptions_status_check",
      sql`${table.status} in ('incomplete', 'trialing', 'active', 'past_due', 'paused', 'canceled', 'unpaid', 'ended')`,
    ),
    check(
      "subscriptions_billing_interval_check",
      sql`${table.billingInterval} is null or ${table.billingInterval} in ('month', 'year')`,
    ),
    check(
      "subscriptions_currency_check",
      sql`${table.currency} is null or length(${table.currency}) = 3`,
    ),
    check(
      "subscriptions_amount_check",
      sql`${table.unitAmountMinor} is null or ${table.unitAmountMinor} >= 0`,
    ),
  ],
);

export const billingEvents = sqliteTable(
  "billing_events",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").references(() => accounts.id, {
      onDelete: "set null",
    }),
    subscriptionId: text("subscription_id").references(() => subscriptions.id, {
      onDelete: "set null",
    }),
    provider: text("provider").notNull(),
    providerEventId: text("provider_event_id").notNull(),
    providerEventType: text("provider_event_type").notNull(),
    status: text("status", { enum: billingEventStatuses })
      .notNull()
      .default("received"),
    payloadSha256: text("payload_sha256").notNull(),
    providerInvoiceId: text("provider_invoice_id"),
    amountMinor: integer("amount_minor"),
    currency: text("currency"),
    eventOccurredAt: timestamp("event_occurred_at"),
    receivedAt: timestamp("received_at").notNull().default(currentTimestampMs),
    processedAt: timestamp("processed_at"),
    leaseToken: text("lease_token"),
    leaseExpiresAt: timestamp("lease_expires_at"),
    lastAttemptAt: timestamp("last_attempt_at"),
    processingAttempts: integer("processing_attempts").notNull().default(0),
    lastErrorCode: text("last_error_code"),
    lastErrorMessage: text("last_error_message"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex("billing_events_provider_event_unique").on(
      table.provider,
      table.providerEventId,
    ),
    index("billing_events_account_received_idx").on(
      table.accountId,
      table.receivedAt,
    ),
    index("billing_events_status_received_idx").on(
      table.status,
      table.receivedAt,
    ),
    check(
      "billing_events_status_check",
      sql`${table.status} in ('received', 'processing', 'processed', 'ignored', 'failed')`,
    ),
    check(
      "billing_events_amount_check",
      sql`${table.amountMinor} is null or ${table.amountMinor} >= 0`,
    ),
    check(
      "billing_events_attempts_check",
      sql`${table.processingAttempts} >= 0`,
    ),
  ],
);

export const billingReconciliationTargets = sqliteTable(
  "billing_reconciliation_targets",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    provider: text("provider").notNull().default("stripe"),
    subscriptionId: text("subscription_id"),
    checkoutAttemptId: text("checkout_attempt_id"),
    state: text("state", {
      enum: billingReconciliationTargetStates,
    }).notNull(),
    leaseToken: text("lease_token"),
    leaseExpiresAt: timestamp("lease_expires_at"),
    lastAttemptAt: timestamp("last_attempt_at").notNull(),
    processingAttempts: integer("processing_attempts").notNull(),
    automaticFailureCount: integer("automatic_failure_count")
      .notNull()
      .default(0),
    nextAutomaticAttemptAt: timestamp("next_automatic_attempt_at"),
    automaticDeadLetteredAt: timestamp("automatic_dead_lettered_at"),
    lastErrorCode: text("last_error_code"),
    lastErrorMessage: text("last_error_message"),
    lastCompletedAt: timestamp("last_completed_at"),
    lastSucceededAt: timestamp("last_succeeded_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "billing_reconciliation_targets_subscription_tenant_fk",
      columns: [table.accountId, table.subscriptionId],
      foreignColumns: [subscriptions.accountId, subscriptions.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "billing_reconciliation_targets_checkout_tenant_fk",
      columns: [table.accountId, table.checkoutAttemptId],
      foreignColumns: [
        billingCheckoutAttempts.accountId,
        billingCheckoutAttempts.id,
      ],
    }).onDelete("cascade"),
    uniqueIndex("billing_reconciliation_targets_subscription_unique")
      .on(table.provider, table.accountId, table.subscriptionId)
      .where(sql`${table.subscriptionId} is not null`),
    uniqueIndex("billing_reconciliation_targets_checkout_unique")
      .on(table.provider, table.accountId, table.checkoutAttemptId)
      .where(sql`${table.checkoutAttemptId} is not null`),
    index("billing_reconciliation_targets_state_lease_idx").on(
      table.state,
      table.leaseExpiresAt,
    ),
    index("billing_reconciliation_targets_account_state_idx").on(
      table.accountId,
      table.state,
    ),
    index("billing_reconciliation_targets_automatic_due_idx").on(
      table.provider,
      table.state,
      table.automaticDeadLetteredAt,
      table.nextAutomaticAttemptAt,
    ),
    check(
      "billing_reconciliation_targets_provider_check",
      sql`${table.provider} = 'stripe'`,
    ),
    check(
      "billing_reconciliation_targets_exact_target_check",
      sql`(${table.subscriptionId} is not null and ${table.checkoutAttemptId} is null) or (${table.subscriptionId} is null and ${table.checkoutAttemptId} is not null)`,
    ),
    check(
      "billing_reconciliation_targets_state_check",
      sql`${table.state} in ('processing', 'succeeded', 'failed')`,
    ),
    check(
      "billing_reconciliation_targets_attempts_check",
      sql`${table.processingAttempts} >= 1`,
    ),
    check(
      "billing_reconciliation_targets_automatic_failures_check",
      sql`${table.automaticFailureCount} >= 0`,
    ),
    check(
      "billing_reconciliation_targets_lease_check",
      sql`(${table.state} = 'processing' and ${table.leaseToken} is not null and ${table.leaseExpiresAt} is not null) or (${table.state} <> 'processing' and ${table.leaseToken} is null and ${table.leaseExpiresAt} is null)`,
    ),
    check(
      "billing_reconciliation_targets_completion_check",
      sql`(${table.state} = 'processing' and ${table.lastCompletedAt} is null) or (${table.state} <> 'processing' and ${table.lastCompletedAt} is not null)`,
    ),
    check(
      "billing_reconciliation_targets_error_check",
      sql`(${table.state} = 'failed' and ${table.lastErrorCode} is not null and ${table.lastErrorMessage} is not null) or (${table.state} <> 'failed' and ${table.lastErrorCode} is null and ${table.lastErrorMessage} is null)`,
    ),
    check(
      "billing_reconciliation_targets_automatic_retry_check",
      sql`(${table.state} = 'failed' and ((${table.automaticDeadLetteredAt} is null and (${table.nextAutomaticAttemptAt} is not null or ${table.automaticFailureCount} = 0)) or (${table.automaticDeadLetteredAt} is not null and ${table.automaticFailureCount} >= 8 and ${table.nextAutomaticAttemptAt} is null))) or (${table.state} <> 'failed' and ${table.nextAutomaticAttemptAt} is null and ${table.automaticDeadLetteredAt} is null)`,
    ),
    check(
      "billing_reconciliation_targets_success_failure_reset_check",
      sql`${table.state} <> 'succeeded' or ${table.automaticFailureCount} = 0`,
    ),
  ],
);

/**
 * One non-tenant scheduler heartbeat. The attempt token fences completion so
 * an older overlapping invocation cannot replace a newer invocation's state.
 * Only bounded counters and normalized machine codes are stored; this table
 * intentionally has no tenant identifiers, provider payloads, or messages.
 */
export const schedulerHeartbeat = sqliteTable(
  "scheduler_heartbeat",
  {
    schedulerKey: text("scheduler_key").primaryKey(),
    attemptToken: text("attempt_token").notNull(),
    releaseId: text("release_id").notNull(),
    state: text("state", { enum: schedulerHeartbeatStates }).notNull(),
    startedAt: timestamp("started_at").notNull(),
    completedAt: timestamp("completed_at"),
    billingConfigured: integer("billing_configured", { mode: "boolean" }),
    consideredCount: integer("considered_count"),
    attemptedCount: integer("attempted_count"),
    succeededCount: integer("succeeded_count"),
    failedCount: integer("failed_count"),
    deadLetterCount: integer("dead_letter_count"),
    lastFailureCode: text("last_failure_code"),
    updatedAt: updatedAt(),
  },
  (table) => [
    check(
      "scheduler_heartbeat_singleton_check",
      sql`${table.schedulerKey} = 'billing_reconciliation'`,
    ),
    check(
      "scheduler_heartbeat_attempt_token_check",
      sql`length(${table.attemptToken}) between 1 and 128 and ${table.attemptToken} not glob '*[^A-Za-z0-9._:-]*'`,
    ),
    check(
      "scheduler_heartbeat_release_id_check",
      sql`length(${table.releaseId}) between 1 and 128 and ${table.releaseId} not glob '*[^A-Za-z0-9._:-]*'`,
    ),
    check(
      "scheduler_heartbeat_state_check",
      sql`${table.state} in ('running', 'succeeded', 'failed')`,
    ),
    check(
      "scheduler_heartbeat_completion_check",
      sql`(${table.state} = 'running' and ${table.completedAt} is null) or (${table.state} <> 'running' and ${table.completedAt} is not null and ${table.completedAt} >= ${table.startedAt})`,
    ),
    check(
      "scheduler_heartbeat_result_shape_check",
      sql`(${table.state} = 'succeeded' and ${table.billingConfigured} is not null and ${table.consideredCount} is not null and ${table.attemptedCount} is not null and ${table.succeededCount} is not null and ${table.failedCount} is not null and ${table.deadLetterCount} is not null and ${table.lastFailureCode} is null) or (${table.state} <> 'succeeded' and ${table.billingConfigured} is null and ${table.consideredCount} is null and ${table.attemptedCount} is null and ${table.succeededCount} is null and ${table.failedCount} is null and ${table.deadLetterCount} is null)`,
    ),
    check(
      "scheduler_heartbeat_failure_check",
      sql`(${table.state} = 'failed' and ${table.lastFailureCode} is not null and length(${table.lastFailureCode}) between 1 and 64 and ${table.lastFailureCode} not glob '*[^a-z0-9_]*') or (${table.state} <> 'failed' and ${table.lastFailureCode} is null)`,
    ),
    check(
      "scheduler_heartbeat_counts_check",
      sql`${table.consideredCount} is null or (${table.consideredCount} >= 0 and ${table.attemptedCount} >= 0 and ${table.succeededCount} >= 0 and ${table.failedCount} >= 0 and ${table.deadLetterCount} >= 0 and ${table.attemptedCount} <= ${table.consideredCount} and ${table.succeededCount} + ${table.failedCount} = ${table.attemptedCount})`,
    ),
  ],
);

/**
 * One durable billing-operation mutex per tenant. Checkout and provider
 * reconciliation both acquire this row before consulting or mutating billing
 * state, so an account cannot create a Checkout Session from a projection
 * that another worker is actively refreshing. Released rows remain in place:
 * terminal D1 batches can then turn a stale claim into a NOT NULL violation
 * instead of silently updating zero rows.
 */
export const billingAccountOperationLeases = sqliteTable(
  "billing_account_operation_leases",
  {
    accountId: text("account_id")
      .primaryKey()
      .references(() => accounts.id, { onDelete: "cascade" }),
    provider: text("provider").notNull().default("stripe"),
    state: text("state", { enum: billingAccountOperationLeaseStates })
      .notNull()
      .default("idle"),
    operation: text("operation", { enum: billingAccountOperationTypes }),
    leaseToken: text("lease_token"),
    leaseGeneration: integer("lease_generation").notNull().default(1),
    leaseExpiresAt: timestamp("lease_expires_at"),
    lastAcquiredAt: timestamp("last_acquired_at"),
    lastReleasedAt: timestamp("last_released_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    index("billing_account_operation_leases_expiry_idx").on(
      table.state,
      table.leaseExpiresAt,
    ),
    check(
      "billing_account_operation_leases_provider_check",
      sql`${table.provider} = 'stripe'`,
    ),
    check(
      "billing_account_operation_leases_state_check",
      sql`${table.state} in ('idle', 'held')`,
    ),
    check(
      "billing_account_operation_leases_operation_check",
      sql`${table.operation} is null or ${table.operation} in ('checkout', 'reconciliation')`,
    ),
    check(
      "billing_account_operation_leases_generation_check",
      sql`${table.leaseGeneration} >= 1`,
    ),
    check(
      "billing_account_operation_leases_shape_check",
      sql`(${table.state} = 'held' and ${table.operation} is not null and ${table.leaseToken} is not null and ${table.leaseExpiresAt} is not null and ${table.lastAcquiredAt} is not null) or (${table.state} = 'idle' and ${table.operation} is null and ${table.leaseToken} is null and ${table.leaseExpiresAt} is null)`,
    ),
  ],
);

export const coachingPackages = sqliteTable(
  "coaching_packages",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    purpose: text("purpose").notNull(),
    fitDescription: text("fit_description").notNull(),
    status: text("status", { enum: packageStatuses })
      .notNull()
      .default("draft"),
    currency: text("currency"),
    priceAmountMinor: integer("price_amount_minor"),
    currentDetailsText: text("current_details_text"),
    inclusions: text("inclusions", { mode: "json" })
      .$type<string[]>()
      .notNull()
      .default(sql`'[]'`),
    cadence: text("cadence"),
    practiceExpectation: text("practice_expectation"),
    evaluationDescription: text("evaluation_description"),
    termsSummary: text("terms_summary"),
    externalActionType: text("external_action_type", {
      enum: ["booking", "purchase", "contact", "other"],
    }).notNull(),
    externalActionLabel: text("external_action_label").notNull(),
    externalActionUrl: text("external_action_url").notNull(),
    externalActionVerifiedAt: timestamp("external_action_verified_at"),
    isDefault: integer("is_default", { mode: "boolean" })
      .notNull()
      .default(false),
    archivedAt: timestamp("archived_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex("coaching_packages_account_id_unique").on(
      table.accountId,
      table.id,
    ),
    uniqueIndex("coaching_packages_one_default_per_account")
      .on(table.accountId)
      .where(sql`${table.isDefault} = 1 and ${table.status} = 'active'`),
    index("coaching_packages_account_status_idx").on(
      table.accountId,
      table.status,
    ),
    check(
      "coaching_packages_status_check",
      sql`${table.status} in ('draft', 'active', 'archived')`,
    ),
    check(
      "coaching_packages_external_action_type_check",
      sql`${table.externalActionType} in ('booking', 'purchase', 'contact', 'other')`,
    ),
    check(
      "coaching_packages_price_check",
      sql`(${table.priceAmountMinor} is null and ${table.currency} is null) or (${table.priceAmountMinor} is not null and ${table.priceAmountMinor} >= 0 and ${table.currency} is not null and length(${table.currency}) = 3)`,
    ),
    check(
      "coaching_packages_details_check",
      sql`${table.priceAmountMinor} is not null or length(trim(coalesce(${table.currentDetailsText}, ''))) > 0`,
    ),
    check(
      "coaching_packages_inclusions_json_check",
      sql`json_valid(${table.inclusions})`,
    ),
  ],
);

export const golfers = sqliteTable(
  "golfers",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    displayName: text("display_name").notNull(),
    preferredName: text("preferred_name"),
    contactEmail: text("contact_email"),
    externalReference: text("external_reference"),
    status: text("status", { enum: golferStatuses })
      .notNull()
      .default("active"),
    eligibilityStatus: text("eligibility_status", {
      enum: ["unconfirmed", "adult_confirmed", "ineligible"],
    })
      .notNull()
      .default("unconfirmed"),
    eligibilityConfirmedAt: timestamp("eligibility_confirmed_at"),
    lastActivityAt: timestamp("last_activity_at"),
    archivedAt: timestamp("archived_at"),
    deletionScheduledAt: timestamp("deletion_scheduled_at"),
    deletedAt: timestamp("deleted_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex("golfers_account_id_unique").on(table.accountId, table.id),
    uniqueIndex("golfers_external_reference_unique")
      .on(table.accountId, table.externalReference)
      .where(sql`${table.externalReference} is not null`),
    index("golfers_account_status_updated_idx").on(
      table.accountId,
      table.status,
      table.updatedAt,
    ),
    index("golfers_account_display_name_idx").on(
      table.accountId,
      table.displayName,
    ),
    check(
      "golfers_status_check",
      sql`${table.status} in ('active', 'inactive', 'archived', 'deletion_pending', 'deleted')`,
    ),
    check(
      "golfers_eligibility_status_check",
      sql`${table.eligibilityStatus} in ('unconfirmed', 'adult_confirmed', 'ineligible')`,
    ),
  ],
);

export const developmentPlans = sqliteTable(
  "development_plans",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    golferId: text("golfer_id").notNull(),
    title: text("title").notNull(),
    status: text("status", { enum: planStatuses })
      .notNull()
      .default("draft"),
    revision: integer("revision").notNull().default(1),
    approvedRevision: integer("approved_revision"),
    publishedRevision: integer("published_revision"),
    welcomeNote: text("welcome_note"),
    assessmentContext: text("assessment_context"),
    currentCoachNote: text("current_coach_note"),
    currentCoachNoteAt: timestamp("current_coach_note_at"),
    privateContextLabel: text("private_context_label")
      .notNull()
      .default("Private coaching roadmap"),
    coachApprovedAt: timestamp("coach_approved_at"),
    previewedAt: timestamp("previewed_at"),
    publishedAt: timestamp("published_at"),
    lastSharedAt: timestamp("last_shared_at"),
    pausedAt: timestamp("paused_at"),
    completedAt: timestamp("completed_at"),
    archivedAt: timestamp("archived_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "development_plans_account_fk",
      columns: [table.accountId],
      foreignColumns: [accounts.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "development_plans_golfer_tenant_fk",
      columns: [table.accountId, table.golferId],
      foreignColumns: [golfers.accountId, golfers.id],
    }).onDelete("cascade"),
    uniqueIndex("development_plans_account_id_unique").on(
      table.accountId,
      table.id,
    ),
    index("development_plans_account_status_updated_idx").on(
      table.accountId,
      table.status,
      table.updatedAt,
    ),
    index("development_plans_golfer_status_idx").on(
      table.accountId,
      table.golferId,
      table.status,
    ),
    check(
      "development_plans_status_check",
      sql`${table.status} in ('draft', 'preview_ready', 'published', 'paused', 'completed', 'archived')`,
    ),
    check("development_plans_revision_check", sql`${table.revision} >= 1`),
    check(
      "development_plans_approved_revision_check",
      sql`${table.approvedRevision} is null or (${table.approvedRevision} >= 1 and ${table.approvedRevision} <= ${table.revision})`,
    ),
    check(
      "development_plans_published_revision_check",
      sql`${table.publishedRevision} is null or (${table.publishedRevision} >= 1 and ${table.publishedRevision} <= ${table.revision})`,
    ),
  ],
);

export const golferGoals = sqliteTable(
  "golfer_goals",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    golferId: text("golfer_id").notNull(),
    planId: text("plan_id").notNull(),
    desiredOutcome: text("desired_outcome").notNull(),
    whyItMatters: text("why_it_matters"),
    context: text("context"),
    constraints: text("constraints"),
    scoreOrHandicapContext: text("score_or_handicap_context"),
    targetDate: timestamp("target_date"),
    status: text("status", { enum: goalStatuses })
      .notNull()
      .default("active"),
    isPrimary: integer("is_primary", { mode: "boolean" })
      .notNull()
      .default(true),
    confirmedByGolferAt: timestamp("confirmed_by_golfer_at"),
    coachApprovedAt: timestamp("coach_approved_at"),
    achievedAt: timestamp("achieved_at"),
    revisedAt: timestamp("revised_at"),
    archivedAt: timestamp("archived_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "golfer_goals_plan_tenant_fk",
      columns: [table.accountId, table.planId],
      foreignColumns: [developmentPlans.accountId, developmentPlans.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "golfer_goals_golfer_tenant_fk",
      columns: [table.accountId, table.golferId],
      foreignColumns: [golfers.accountId, golfers.id],
    }).onDelete("cascade"),
    uniqueIndex("golfer_goals_account_id_unique").on(table.accountId, table.id),
    uniqueIndex("golfer_goals_one_primary_per_plan")
      .on(table.accountId, table.planId)
      .where(sql`${table.isPrimary} = 1 and ${table.status} = 'active'`),
    index("golfer_goals_golfer_status_idx").on(
      table.accountId,
      table.golferId,
      table.status,
    ),
    check(
      "golfer_goals_status_check",
      sql`${table.status} in ('active', 'achieved', 'revised', 'archived')`,
    ),
  ],
);

export const assessments = sqliteTable(
  "assessments",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    planId: text("plan_id").notNull(),
    title: text("title").notNull(),
    status: text("status", { enum: assessmentStatuses })
      .notNull()
      .default("draft"),
    assessedAt: timestamp("assessed_at"),
    context: text("context"),
    startingPoint: text("starting_point").notNull(),
    strengthSummary: text("strength_summary").notNull(),
    primaryPattern: text("primary_pattern").notNull(),
    limitations: text("limitations"),
    coachApprovedAt: timestamp("coach_approved_at"),
    supersededAt: timestamp("superseded_at"),
    archivedAt: timestamp("archived_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "assessments_plan_tenant_fk",
      columns: [table.accountId, table.planId],
      foreignColumns: [developmentPlans.accountId, developmentPlans.id],
    }).onDelete("cascade"),
    uniqueIndex("assessments_account_id_unique").on(table.accountId, table.id),
    index("assessments_plan_status_idx").on(
      table.accountId,
      table.planId,
      table.status,
    ),
    index("assessments_assessed_at_idx").on(table.assessedAt),
    check(
      "assessments_status_check",
      sql`${table.status} in ('draft', 'confirmed', 'superseded', 'archived')`,
    ),
  ],
);

export const planPriorities = sqliteTable(
  "plan_priorities",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    planId: text("plan_id").notNull(),
    assessmentId: text("assessment_id"),
    title: text("title").notNull(),
    description: text("description").notNull(),
    rationale: text("rationale"),
    status: text("status", { enum: priorityStatuses })
      .notNull()
      .default("active"),
    sortOrder: integer("sort_order").notNull().default(0),
    isCurrent: integer("is_current", { mode: "boolean" })
      .notNull()
      .default(false),
    coachApprovedAt: timestamp("coach_approved_at"),
    resolvedAt: timestamp("resolved_at"),
    archivedAt: timestamp("archived_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "plan_priorities_plan_tenant_fk",
      columns: [table.accountId, table.planId],
      foreignColumns: [developmentPlans.accountId, developmentPlans.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "plan_priorities_assessment_tenant_fk",
      columns: [table.accountId, table.assessmentId],
      foreignColumns: [assessments.accountId, assessments.id],
    }).onDelete("no action"),
    uniqueIndex("plan_priorities_account_id_unique").on(
      table.accountId,
      table.id,
    ),
    uniqueIndex("plan_priorities_one_current_per_plan")
      .on(table.accountId, table.planId)
      .where(sql`${table.isCurrent} = 1 and ${table.status} = 'active'`),
    index("plan_priorities_plan_order_idx").on(
      table.accountId,
      table.planId,
      table.sortOrder,
    ),
    check(
      "plan_priorities_status_check",
      sql`${table.status} in ('active', 'resolved', 'deferred', 'archived')`,
    ),
    check("plan_priorities_sort_order_check", sql`${table.sortOrder} >= 0`),
  ],
);

export const planPhases = sqliteTable(
  "plan_phases",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    planId: text("plan_id").notNull(),
    coachingPackageId: text("coaching_package_id"),
    sequence: integer("sequence").notNull(),
    title: text("title").notNull(),
    purpose: text("purpose").notNull(),
    rationale: text("rationale"),
    progressSignals: text("progress_signals", { mode: "json" })
      .$type<string[]>()
      .notNull()
      .default(sql`'[]'`),
    expectations: text("expectations"),
    estimatedDuration: text("estimated_duration"),
    status: text("status", { enum: phaseStatuses })
      .notNull()
      .default("planned"),
    isRecommended: integer("is_recommended", { mode: "boolean" })
      .notNull()
      .default(false),
    coachApprovedAt: timestamp("coach_approved_at"),
    startedAt: timestamp("started_at"),
    pausedAt: timestamp("paused_at"),
    completedAt: timestamp("completed_at"),
    revisedAt: timestamp("revised_at"),
    canceledAt: timestamp("canceled_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "plan_phases_plan_tenant_fk",
      columns: [table.accountId, table.planId],
      foreignColumns: [developmentPlans.accountId, developmentPlans.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "plan_phases_package_tenant_fk",
      columns: [table.accountId, table.coachingPackageId],
      foreignColumns: [coachingPackages.accountId, coachingPackages.id],
    }).onDelete("no action"),
    uniqueIndex("plan_phases_account_id_unique").on(table.accountId, table.id),
    uniqueIndex("plan_phases_sequence_unique").on(
      table.accountId,
      table.planId,
      table.sequence,
    ),
    uniqueIndex("plan_phases_one_active_per_plan")
      .on(table.accountId, table.planId)
      .where(sql`${table.status} = 'active'`),
    index("plan_phases_plan_status_idx").on(
      table.accountId,
      table.planId,
      table.status,
    ),
    check(
      "plan_phases_status_check",
      sql`${table.status} in ('planned', 'active', 'paused', 'complete', 'revised', 'canceled')`,
    ),
    check("plan_phases_sequence_check", sql`${table.sequence} >= 1`),
    check(
      "plan_phases_progress_signals_json_check",
      sql`json_valid(${table.progressSignals})`,
    ),
  ],
);

export const phasePriorities = sqliteTable(
  "phase_priorities",
  {
    accountId: text("account_id").notNull(),
    phaseId: text("phase_id").notNull(),
    priorityId: text("priority_id").notNull(),
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: createdAt(),
  },
  (table) => [
    foreignKey({
      name: "phase_priorities_phase_tenant_fk",
      columns: [table.accountId, table.phaseId],
      foreignColumns: [planPhases.accountId, planPhases.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "phase_priorities_priority_tenant_fk",
      columns: [table.accountId, table.priorityId],
      foreignColumns: [planPriorities.accountId, planPriorities.id],
    }).onDelete("cascade"),
    uniqueIndex("phase_priorities_pair_unique").on(
      table.accountId,
      table.phaseId,
      table.priorityId,
    ),
    index("phase_priorities_phase_order_idx").on(
      table.accountId,
      table.phaseId,
      table.sortOrder,
    ),
    check("phase_priorities_sort_order_check", sql`${table.sortOrder} >= 0`),
  ],
);

export const lessons = sqliteTable(
  "lessons",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    planId: text("plan_id").notNull(),
    phaseId: text("phase_id"),
    sequence: integer("sequence").notNull(),
    title: text("title").notNull(),
    status: text("status", { enum: lessonStatuses })
      .notNull()
      .default("planned"),
    purpose: text("purpose").notNull(),
    coachObservation: text("coach_observation"),
    golferLearning: text("golfer_learning"),
    takeaway: text("takeaway"),
    nextCheck: text("next_check"),
    phaseConnection: text("phase_connection"),
    scheduledAt: timestamp("scheduled_at"),
    occurredAt: timestamp("occurred_at"),
    coachApprovedAt: timestamp("coach_approved_at"),
    completedAt: timestamp("completed_at"),
    canceledAt: timestamp("canceled_at"),
    archivedAt: timestamp("archived_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "lessons_plan_tenant_fk",
      columns: [table.accountId, table.planId],
      foreignColumns: [developmentPlans.accountId, developmentPlans.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "lessons_phase_tenant_fk",
      columns: [table.accountId, table.phaseId],
      foreignColumns: [planPhases.accountId, planPhases.id],
    }).onDelete("no action"),
    uniqueIndex("lessons_account_id_unique").on(table.accountId, table.id),
    uniqueIndex("lessons_plan_sequence_unique").on(
      table.accountId,
      table.planId,
      table.sequence,
    ),
    index("lessons_plan_status_idx").on(
      table.accountId,
      table.planId,
      table.status,
    ),
    index("lessons_phase_sequence_idx").on(
      table.accountId,
      table.phaseId,
      table.sequence,
    ),
    check(
      "lessons_status_check",
      sql`${table.status} in ('planned', 'completed', 'canceled', 'archived')`,
    ),
    check("lessons_sequence_check", sql`${table.sequence} >= 1`),
  ],
);

export const practiceItems = sqliteTable(
  "practice_items",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    planId: text("plan_id").notNull(),
    phaseId: text("phase_id"),
    lessonId: text("lesson_id"),
    title: text("title").notNull(),
    status: text("status", { enum: practiceStatuses })
      .notNull()
      .default("draft"),
    objective: text("objective").notNull(),
    rationale: text("rationale").notNull(),
    instructions: text("instructions", { mode: "json" })
      .$type<string[]>()
      .notNull()
      .default(sql`'[]'`),
    timeOrCadence: text("time_or_cadence"),
    successCheck: text("success_check").notNull(),
    commonMistake: text("common_mistake"),
    stopOrAskRule: text("stop_or_ask_rule").notNull(),
    constraintNote: text("constraint_note"),
    startsAt: timestamp("starts_at"),
    dueAt: timestamp("due_at"),
    coachApprovedAt: timestamp("coach_approved_at"),
    completedAt: timestamp("completed_at"),
    retiredAt: timestamp("retired_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "practice_items_plan_tenant_fk",
      columns: [table.accountId, table.planId],
      foreignColumns: [developmentPlans.accountId, developmentPlans.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "practice_items_phase_tenant_fk",
      columns: [table.accountId, table.phaseId],
      foreignColumns: [planPhases.accountId, planPhases.id],
    }).onDelete("no action"),
    foreignKey({
      name: "practice_items_lesson_tenant_fk",
      columns: [table.accountId, table.lessonId],
      foreignColumns: [lessons.accountId, lessons.id],
    }).onDelete("no action"),
    uniqueIndex("practice_items_account_id_unique").on(table.accountId, table.id),
    index("practice_items_plan_status_due_idx").on(
      table.accountId,
      table.planId,
      table.status,
      table.dueAt,
    ),
    index("practice_items_phase_status_idx").on(
      table.accountId,
      table.phaseId,
      table.status,
    ),
    check(
      "practice_items_status_check",
      sql`${table.status} in ('draft', 'active', 'completed', 'paused', 'retired')`,
    ),
    check(
      "practice_items_instructions_json_check",
      sql`json_valid(${table.instructions})`,
    ),
  ],
);

export const evidenceItems = sqliteTable(
  "evidence_items",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    planId: text("plan_id").notNull(),
    assessmentId: text("assessment_id"),
    phaseId: text("phase_id"),
    lessonId: text("lesson_id"),
    practiceItemId: text("practice_item_id"),
    mediaAssetId: text("media_asset_id"),
    status: text("status", { enum: evidenceStatuses })
      .notNull()
      .default("draft"),
    evidenceType: text("evidence_type", {
      enum: [
        "coach_observation",
        "golfer_report",
        "measurement",
        "outcome_count",
        "media",
        "comparison",
        "note",
      ],
    }).notNull(),
    contextType: text("context_type", {
      enum: [
        "assessment",
        "lesson",
        "practice",
        "on_course",
        "phase_review",
        "other",
      ],
    }).notNull(),
    title: text("title").notNull(),
    claim: text("claim"),
    sourceLabel: text("source_label").notNull(),
    sourceType: text("source_type", {
      enum: ["coach_observed", "golfer_reported", "device", "document", "mixed"],
    }).notNull(),
    observedAt: timestamp("observed_at"),
    comparisonRole: text("comparison_role", {
      enum: ["standalone", "baseline", "current"],
    })
      .notNull()
      .default("standalone"),
    comparisonGroupId: text("comparison_group_id"),
    metricName: text("metric_name"),
    metricValue: real("metric_value"),
    metricUnit: text("metric_unit"),
    valueText: text("value_text"),
    interpretation: text("interpretation").notNull(),
    limitation: text("limitation").notNull(),
    maturity: text("maturity", {
      enum: [
        "single_observation",
        "early_indication",
        "repeated_practice",
        "on_course_observation",
        "insufficient",
      ],
    }).notNull(),
    nextEvidenceNeeded: text("next_evidence_needed"),
    isRepresentative: integer("is_representative", { mode: "boolean" })
      .notNull()
      .default(false),
    coachApprovedAt: timestamp("coach_approved_at"),
    withdrawnAt: timestamp("withdrawn_at"),
    archivedAt: timestamp("archived_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "evidence_items_plan_tenant_fk",
      columns: [table.accountId, table.planId],
      foreignColumns: [developmentPlans.accountId, developmentPlans.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "evidence_items_assessment_tenant_fk",
      columns: [table.accountId, table.assessmentId],
      foreignColumns: [assessments.accountId, assessments.id],
    }).onDelete("no action"),
    foreignKey({
      name: "evidence_items_phase_tenant_fk",
      columns: [table.accountId, table.phaseId],
      foreignColumns: [planPhases.accountId, planPhases.id],
    }).onDelete("no action"),
    foreignKey({
      name: "evidence_items_lesson_tenant_fk",
      columns: [table.accountId, table.lessonId],
      foreignColumns: [lessons.accountId, lessons.id],
    }).onDelete("no action"),
    foreignKey({
      name: "evidence_items_practice_tenant_fk",
      columns: [table.accountId, table.practiceItemId],
      foreignColumns: [practiceItems.accountId, practiceItems.id],
    }).onDelete("no action"),
    foreignKey({
      name: "evidence_items_media_tenant_fk",
      columns: [table.accountId, table.mediaAssetId],
      foreignColumns: [mediaAssets.accountId, mediaAssets.id],
    }).onDelete("no action"),
    uniqueIndex("evidence_items_account_id_unique").on(table.accountId, table.id),
    index("evidence_items_plan_status_observed_idx").on(
      table.accountId,
      table.planId,
      table.status,
      table.observedAt,
    ),
    index("evidence_items_phase_status_idx").on(
      table.accountId,
      table.phaseId,
      table.status,
    ),
    index("evidence_items_comparison_group_idx").on(
      table.accountId,
      table.comparisonGroupId,
    ),
    check(
      "evidence_items_status_check",
      sql`${table.status} in ('draft', 'published', 'withdrawn', 'archived')`,
    ),
    check(
      "evidence_items_type_check",
      sql`${table.evidenceType} in ('coach_observation', 'golfer_report', 'measurement', 'outcome_count', 'media', 'comparison', 'note')`,
    ),
    check(
      "evidence_items_context_check",
      sql`${table.contextType} in ('assessment', 'lesson', 'practice', 'on_course', 'phase_review', 'other')`,
    ),
    check(
      "evidence_items_source_type_check",
      sql`${table.sourceType} in ('coach_observed', 'golfer_reported', 'device', 'document', 'mixed')`,
    ),
    check(
      "evidence_items_comparison_role_check",
      sql`${table.comparisonRole} in ('standalone', 'baseline', 'current')`,
    ),
    check(
      "evidence_items_maturity_check",
      sql`${table.maturity} in ('single_observation', 'early_indication', 'repeated_practice', 'on_course_observation', 'insufficient')`,
    ),
    check(
      "evidence_items_metric_check",
      sql`(${table.metricValue} is null and ${table.metricName} is null and ${table.metricUnit} is null) or (${table.metricValue} is not null and length(trim(coalesce(${table.metricName}, ''))) > 0)`,
    ),
    check(
      "evidence_items_media_check",
      sql`${table.evidenceType} <> 'media' or ${table.mediaAssetId} is not null`,
    ),
  ],
);

export const phaseReviews = sqliteTable(
  "phase_reviews",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    planId: text("plan_id").notNull(),
    phaseId: text("phase_id").notNull(),
    nextPhaseId: text("next_phase_id"),
    recommendedPackageId: text("recommended_package_id"),
    status: text("status", { enum: phaseReviewStatuses })
      .notNull()
      .default("draft"),
    outcome: text("outcome", {
      enum: [
        "complete",
        "partially_complete",
        "paused",
        "revised",
        "insufficient_evidence",
        "goal_changed",
      ],
    }).notNull(),
    originalPurpose: text("original_purpose").notNull(),
    baselineSummary: text("baseline_summary").notNull(),
    workCompleted: text("work_completed").notNull(),
    changeSummary: text("change_summary").notNull(),
    reliabilityLabel: text("reliability_label").notNull(),
    limitations: text("limitations").notNull(),
    golferContribution: text("golfer_contribution"),
    coachConclusion: text("coach_conclusion").notNull(),
    remainingOpportunity: text("remaining_opportunity"),
    nextPhaseRationale: text("next_phase_rationale"),
    independentPracticeAlternative: text("independent_practice_alternative"),
    confirmedAt: timestamp("confirmed_at"),
    sharedAt: timestamp("shared_at"),
    supersededAt: timestamp("superseded_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "phase_reviews_plan_tenant_fk",
      columns: [table.accountId, table.planId],
      foreignColumns: [developmentPlans.accountId, developmentPlans.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "phase_reviews_phase_tenant_fk",
      columns: [table.accountId, table.phaseId],
      foreignColumns: [planPhases.accountId, planPhases.id],
    }).onDelete("no action"),
    foreignKey({
      name: "phase_reviews_next_phase_tenant_fk",
      columns: [table.accountId, table.nextPhaseId],
      foreignColumns: [planPhases.accountId, planPhases.id],
    }).onDelete("no action"),
    foreignKey({
      name: "phase_reviews_package_tenant_fk",
      columns: [table.accountId, table.recommendedPackageId],
      foreignColumns: [coachingPackages.accountId, coachingPackages.id],
    }).onDelete("no action"),
    uniqueIndex("phase_reviews_account_id_unique").on(table.accountId, table.id),
    index("phase_reviews_phase_status_idx").on(
      table.accountId,
      table.phaseId,
      table.status,
    ),
    index("phase_reviews_plan_created_idx").on(
      table.accountId,
      table.planId,
      table.createdAt,
    ),
    check(
      "phase_reviews_status_check",
      sql`${table.status} in ('draft', 'confirmed', 'shared', 'superseded')`,
    ),
    check(
      "phase_reviews_outcome_check",
      sql`${table.outcome} in ('complete', 'partially_complete', 'paused', 'revised', 'insufficient_evidence', 'goal_changed')`,
    ),
  ],
);

export const phaseReviewEvidence = sqliteTable(
  "phase_review_evidence",
  {
    accountId: text("account_id").notNull(),
    phaseReviewId: text("phase_review_id").notNull(),
    evidenceItemId: text("evidence_item_id").notNull(),
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: createdAt(),
  },
  (table) => [
    foreignKey({
      name: "phase_review_evidence_review_tenant_fk",
      columns: [table.accountId, table.phaseReviewId],
      foreignColumns: [phaseReviews.accountId, phaseReviews.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "phase_review_evidence_item_tenant_fk",
      columns: [table.accountId, table.evidenceItemId],
      foreignColumns: [evidenceItems.accountId, evidenceItems.id],
    }).onDelete("cascade"),
    uniqueIndex("phase_review_evidence_pair_unique").on(
      table.accountId,
      table.phaseReviewId,
      table.evidenceItemId,
    ),
    index("phase_review_evidence_review_order_idx").on(
      table.accountId,
      table.phaseReviewId,
      table.sortOrder,
    ),
    check(
      "phase_review_evidence_sort_order_check",
      sql`${table.sortOrder} >= 0`,
    ),
  ],
);

export const shareLinks = sqliteTable(
  "share_links",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    planId: text("plan_id").notNull(),
    // The URL bearer token is returned once and never persisted. Store only its
    // peppered HMAC-SHA-256 fingerprint (hex encoded).
    tokenHash: text("token_hash").notNull(),
    tokenHashAlgorithm: text("token_hash_algorithm")
      .notNull()
      .default("hmac-sha256-v1"),
    status: text("status", { enum: shareLinkStatuses })
      .notNull()
      .default("active"),
    scope: text("scope", { enum: ["golfer_plan_read"] })
      .notNull()
      .default("golfer_plan_read"),
    planRevision: integer("plan_revision").notNull(),
    intendedRecipientContext: text("intended_recipient_context").notNull(),
    expiresAt: timestamp("expires_at"),
    lastAccessedAt: timestamp("last_accessed_at"),
    accessCount: integer("access_count").notNull().default(0),
    revokedAt: timestamp("revoked_at"),
    revokeReason: text("revoke_reason"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "share_links_plan_tenant_fk",
      columns: [table.accountId, table.planId],
      foreignColumns: [developmentPlans.accountId, developmentPlans.id],
    }).onDelete("cascade"),
    uniqueIndex("share_links_token_hash_unique").on(table.tokenHash),
    uniqueIndex("share_links_account_id_unique").on(table.accountId, table.id),
    index("share_links_plan_status_idx").on(
      table.accountId,
      table.planId,
      table.status,
    ),
    index("share_links_status_expires_idx").on(table.status, table.expiresAt),
    check(
      "share_links_status_check",
      sql`${table.status} in ('active', 'revoked', 'expired')`,
    ),
    check(
      "share_links_scope_check",
      sql`${table.scope} = 'golfer_plan_read'`,
    ),
    check(
      "share_links_token_hash_algorithm_check",
      sql`${table.tokenHashAlgorithm} = 'hmac-sha256-v1'`,
    ),
    check(
      "share_links_token_hash_check",
      sql`length(${table.tokenHash}) = 64 and ${table.tokenHash} not glob '*[^0-9a-f]*'`,
    ),
    check("share_links_revision_check", sql`${table.planRevision} >= 1`),
    check("share_links_access_count_check", sql`${table.accessCount} >= 0`),
  ],
);

export const shareSessions = sqliteTable(
  "share_sessions",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    shareLinkId: text("share_link_id").notNull(),
    // Browser cookies contain a session-only random value. D1 stores only its
    // domain-separated, peppered HMAC-SHA-256 fingerprint.
    tokenHash: text("token_hash").notNull(),
    tokenHashAlgorithm: text("token_hash_algorithm")
      .notNull()
      .default("hmac-sha256-session-v1"),
    expiresAt: timestamp("expires_at").notNull(),
    lastAccessedAt: timestamp("last_accessed_at"),
    accessCount: integer("access_count").notNull().default(0),
    revokedAt: timestamp("revoked_at"),
    revokeReason: text("revoke_reason"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "share_sessions_share_tenant_fk",
      columns: [table.accountId, table.shareLinkId],
      foreignColumns: [shareLinks.accountId, shareLinks.id],
    }).onDelete("cascade"),
    uniqueIndex("share_sessions_token_hash_unique").on(table.tokenHash),
    uniqueIndex("share_sessions_account_id_unique").on(table.accountId, table.id),
    index("share_sessions_share_created_idx").on(
      table.accountId,
      table.shareLinkId,
      table.createdAt,
    ),
    index("share_sessions_expiry_revocation_idx").on(
      table.expiresAt,
      table.revokedAt,
    ),
    check(
      "share_sessions_token_hash_algorithm_check",
      sql`${table.tokenHashAlgorithm} = 'hmac-sha256-session-v1'`,
    ),
    check(
      "share_sessions_token_hash_check",
      sql`length(${table.tokenHash}) = 64 and ${table.tokenHash} not glob '*[^0-9a-f]*'`,
    ),
    check(
      "share_sessions_expiry_check",
      sql`${table.expiresAt} > ${table.createdAt}`,
    ),
    check("share_sessions_access_count_check", sql`${table.accessCount} >= 0`),
    check(
      "share_sessions_revocation_check",
      sql`(${table.revokedAt} is null and ${table.revokeReason} is null) or (${table.revokedAt} is not null and length(trim(coalesce(${table.revokeReason}, ''))) > 0)`,
    ),
  ],
);

export const golferPlanResponses = sqliteTable(
  "golfer_plan_responses",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    planId: text("plan_id").notNull(),
    shareLinkId: text("share_link_id"),
    responseType: text("response_type", {
      enum: [
        "ask_question",
        "wait",
        "decline",
        "request_reassessment",
        "independent_practice",
        "external_action_opened",
      ],
    }).notNull(),
    note: text("note"),
    // Opening an external route is not evidence of a booking, payment, or sale.
    externalOutcomeObserved: integer("external_outcome_observed", {
      mode: "boolean",
    })
      .notNull()
      .default(false),
    occurredAt: timestamp("occurred_at").notNull().default(currentTimestampMs),
    createdAt: createdAt(),
  },
  (table) => [
    foreignKey({
      name: "golfer_plan_responses_plan_tenant_fk",
      columns: [table.accountId, table.planId],
      foreignColumns: [developmentPlans.accountId, developmentPlans.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "golfer_plan_responses_share_tenant_fk",
      columns: [table.accountId, table.shareLinkId],
      foreignColumns: [shareLinks.accountId, shareLinks.id],
    }).onDelete("no action"),
    uniqueIndex("golfer_plan_responses_account_id_unique").on(
      table.accountId,
      table.id,
    ),
    index("golfer_plan_responses_plan_occurred_idx").on(
      table.accountId,
      table.planId,
      table.occurredAt,
    ),
    check(
      "golfer_plan_responses_type_check",
      sql`${table.responseType} in ('ask_question', 'wait', 'decline', 'request_reassessment', 'independent_practice', 'external_action_opened')`,
    ),
    check(
      "golfer_plan_responses_external_outcome_check",
      sql`${table.externalOutcomeObserved} = 0`,
    ),
  ],
);

export const consentRecords = sqliteTable(
  "consent_records",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    golferId: text("golfer_id"),
    subjectType: text("subject_type", { enum: ["account", "golfer"] }).notNull(),
    scope: text("scope", {
      enum: [
        "terms",
        "privacy_notice",
        "golfer_record",
        "roadmap_sharing",
        "media_use",
        "service_email",
        "optional_analytics",
      ],
    }).notNull(),
    status: text("status", { enum: consentStatuses }).notNull(),
    policyVersion: text("policy_version").notNull(),
    purposeDescription: text("purpose_description").notNull(),
    captureMethod: text("capture_method", {
      enum: ["self_service", "instructor_attested", "support_assisted", "imported"],
    }).notNull(),
    evidenceReference: text("evidence_reference"),
    recordedByAccountId: text("recorded_by_account_id").references(
      () => accounts.id,
      { onDelete: "set null" },
    ),
    grantedAt: timestamp("granted_at"),
    declinedAt: timestamp("declined_at"),
    withdrawnAt: timestamp("withdrawn_at"),
    expiresAt: timestamp("expires_at"),
    createdAt: createdAt(),
  },
  (table) => [
    foreignKey({
      name: "consent_records_account_fk",
      columns: [table.accountId],
      foreignColumns: [accounts.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "consent_records_golfer_tenant_fk",
      columns: [table.accountId, table.golferId],
      foreignColumns: [golfers.accountId, golfers.id],
    }).onDelete("no action"),
    uniqueIndex("consent_records_account_id_unique").on(table.accountId, table.id),
    index("consent_records_subject_scope_created_idx").on(
      table.accountId,
      table.golferId,
      table.scope,
      table.createdAt,
    ),
    index("consent_records_status_expires_idx").on(table.status, table.expiresAt),
    check(
      "consent_records_subject_type_check",
      sql`${table.subjectType} in ('account', 'golfer')`,
    ),
    check(
      "consent_records_subject_reference_check",
      sql`(${table.subjectType} = 'account' and ${table.golferId} is null) or (${table.subjectType} = 'golfer' and ${table.golferId} is not null)`,
    ),
    check(
      "consent_records_scope_check",
      sql`${table.scope} in ('terms', 'privacy_notice', 'golfer_record', 'roadmap_sharing', 'media_use', 'service_email', 'optional_analytics')`,
    ),
    check(
      "consent_records_status_check",
      sql`${table.status} in ('granted', 'declined', 'withdrawn', 'expired')`,
    ),
    check(
      "consent_records_capture_method_check",
      sql`${table.captureMethod} in ('self_service', 'instructor_attested', 'support_assisted', 'imported')`,
    ),
    check(
      "consent_records_status_timestamp_consistency_check",
      sql`(
        ${table.status} = 'granted'
        and ${table.grantedAt} is not null
        and ${table.grantedAt} <= ${table.createdAt}
        and ${table.declinedAt} is null
        and ${table.withdrawnAt} is null
        and (${table.expiresAt} is null or ${table.expiresAt} > ${table.grantedAt})
      ) or (
        ${table.status} = 'declined'
        and ${table.grantedAt} is null
        and ${table.declinedAt} is not null
        and ${table.declinedAt} <= ${table.createdAt}
        and ${table.withdrawnAt} is null
        and ${table.expiresAt} is null
      ) or (
        ${table.status} = 'withdrawn'
        and ${table.grantedAt} is null
        and ${table.declinedAt} is null
        and ${table.withdrawnAt} is not null
        and ${table.withdrawnAt} <= ${table.createdAt}
        and ${table.expiresAt} is null
      ) or (
        ${table.status} = 'expired'
        and ${table.grantedAt} is null
        and ${table.declinedAt} is null
        and ${table.withdrawnAt} is null
        and ${table.expiresAt} is not null
        and ${table.expiresAt} <= ${table.createdAt}
      )`,
    ),
  ],
);

export const auditEvents = sqliteTable(
  "audit_events",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").references(() => accounts.id, {
      onDelete: "set null",
    }),
    actorType: text("actor_type", {
      enum: ["account", "golfer_share", "system", "support", "billing_provider"],
    }).notNull(),
    actorAccountId: text("actor_account_id").references(() => accounts.id, {
      onDelete: "set null",
    }),
    actorReference: text("actor_reference"),
    action: text("action").notNull(),
    targetType: text("target_type").notNull(),
    targetId: text("target_id"),
    outcome: text("outcome", { enum: ["success", "failure", "denied"] }).notNull(),
    requestId: text("request_id"),
    ipAddressHash: text("ip_address_hash"),
    metadata: text("metadata", { mode: "json" }).$type<Record<string, unknown>>(),
    occurredAt: timestamp("occurred_at").notNull().default(currentTimestampMs),
    retentionExpiresAt: timestamp("retention_expires_at"),
  },
  (table) => [
    index("audit_events_account_occurred_idx").on(
      table.accountId,
      table.occurredAt,
    ),
    index("audit_events_actor_occurred_idx").on(
      table.actorAccountId,
      table.occurredAt,
    ),
    index("audit_events_target_occurred_idx").on(
      table.targetType,
      table.targetId,
      table.occurredAt,
    ),
    index("audit_events_action_outcome_idx").on(table.action, table.outcome),
    index("audit_events_retention_expires_idx").on(table.retentionExpiresAt),
    check(
      "audit_events_actor_type_check",
      sql`${table.actorType} in ('account', 'golfer_share', 'system', 'support', 'billing_provider')`,
    ),
    check(
      "audit_events_outcome_check",
      sql`${table.outcome} in ('success', 'failure', 'denied')`,
    ),
    check(
      "audit_events_metadata_json_check",
      sql`${table.metadata} is null or json_valid(${table.metadata})`,
    ),
  ],
);

export const dataRequests = sqliteTable(
  "data_requests",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").references(() => accounts.id, {
      onDelete: "set null",
    }),
    golferId: text("golfer_id"),
    requestType: text("request_type", {
      enum: [
        "access",
        "export",
        "correction",
        "deletion",
        "restriction",
        "consent_withdrawal",
      ],
    }).notNull(),
    requestedByType: text("requested_by_type", {
      enum: ["account", "golfer", "authorized_representative", "support"],
    }).notNull(),
    requesterContactHash: text("requester_contact_hash"),
    status: text("status", { enum: dataRequestStatuses })
      .notNull()
      .default("submitted"),
    details: text("details"),
    identityVerifiedAt: timestamp("identity_verified_at"),
    dueAt: timestamp("due_at"),
    assignedToReference: text("assigned_to_reference"),
    decisionReason: text("decision_reason"),
    exportObjectKey: text("export_object_key"),
    exportSha256: text("export_sha256"),
    exportExpiresAt: timestamp("export_expires_at"),
    deletionScheduledAt: timestamp("deletion_scheduled_at"),
    fulfilledAt: timestamp("fulfilled_at"),
    canceledAt: timestamp("canceled_at"),
    failedAt: timestamp("failed_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    foreignKey({
      name: "data_requests_golfer_tenant_fk",
      columns: [table.accountId, table.golferId],
      foreignColumns: [golfers.accountId, golfers.id],
    }).onDelete("no action"),
    index("data_requests_account_created_idx").on(
      table.accountId,
      table.createdAt,
    ),
    index("data_requests_golfer_created_idx").on(
      table.golferId,
      table.createdAt,
    ),
    index("data_requests_status_due_idx").on(table.status, table.dueAt),
    check(
      "data_requests_type_check",
      sql`${table.requestType} in ('access', 'export', 'correction', 'deletion', 'restriction', 'consent_withdrawal')`,
    ),
    check(
      "data_requests_requester_type_check",
      sql`${table.requestedByType} in ('account', 'golfer', 'authorized_representative', 'support')`,
    ),
    check(
      "data_requests_status_check",
      sql`${table.status} in ('submitted', 'identity_verification_required', 'verified', 'in_progress', 'fulfilled', 'denied', 'canceled', 'failed')`,
    ),
    check(
      "data_requests_export_fields_check",
      sql`${table.exportObjectKey} is null or ${table.requestType} in ('access', 'export')`,
    ),
  ],
);

export const abuseRateLimits = sqliteTable(
  "abuse_rate_limits",
  {
    scope: text("scope", { enum: abuseLimitScopes }).notNull(),
    // Subjects (network addresses, capability verifiers, and account IDs) are
    // HMAC-SHA-256 digests before they reach D1. Raw identifiers are never
    // written to this short-lived operational table.
    subjectKeyHash: text("subject_key_hash").notNull(),
    windowStartedAt: timestamp("window_started_at").notNull(),
    windowExpiresAt: timestamp("window_expires_at").notNull(),
    requestCount: integer("request_count").notNull().default(1),
    lastRequestAt: timestamp("last_request_at").notNull(),
  },
  (table) => [
    primaryKey({
      name: "abuse_rate_limits_pk",
      columns: [table.scope, table.subjectKeyHash, table.windowStartedAt],
    }),
    index("abuse_rate_limits_expires_idx").on(table.windowExpiresAt),
    check(
      "abuse_rate_limits_scope_check",
      sql`${table.scope} in ('share_exchange_network', 'share_exchange_capability', 'share_close_network', 'share_close_session', 'share_response_network', 'share_response_capability', 'plan_publish_account', 'share_revoke_account', 'billing_checkout_account', 'billing_portal_account', 'billing_reconcile_account', 'data_export_account', 'data_request_account', 'data_request_operator_network', 'data_request_operator_identity')`,
    ),
    check(
      "abuse_rate_limits_hash_check",
      sql`length(${table.subjectKeyHash}) = 64 and ${table.subjectKeyHash} not glob '*[^0-9a-f]*'`,
    ),
    check(
      "abuse_rate_limits_window_check",
      sql`${table.windowExpiresAt} > ${table.windowStartedAt}`,
    ),
    check(
      "abuse_rate_limits_count_check",
      sql`${table.requestCount} >= 1`,
    ),
  ],
);
